<!DOCTYPE html>
<html>
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <style>
	.b {
	  font: normal small-caps normal 1em/120% Arial, Helvetica, sans-serif;
	}
	
	p{
		font: 12px arial, sans-serif;
	}
	
	.small {
		font: italic 0.8em arial, sans-serif;
	}
</style>
    </head>
    
    
    
    <body>
    	<div><img src="cid:vnsnyThumbNail" /></div>
    	
    	<p>IMPORTANT: NOTIFICATION OF NEW WEB PORTAL REFERRAL</p>
      	<p>
      		DATE: ${refdate} </br>
      		TIME: ${reftime}
      	</p>
          
      <p>
     THIS IS TO NOTIFY YOU THERE IS A NEW WEB PORTAL REFERRAL TO REVIEW FOR VNSNY HOSPICE CARE. PLEASE REVIEW AS SOON AS POSSIBLE FOR POTENTIAL HOSPICE ADMISSION.
     </p>
     
	
	<pre class="b">
${referJsonData}
	</pre>	
<p>
THANK YOU
</p>

<div class="small">
This electronic message is intended to be for the use only of the named recipient, and may contain information from Visiting Nurse Service of New York and/or its affiliates and subsidiaries ("VNSNY") that is confidential or privileged, or protected health information from VNSNY that is confidential under HIPAA. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of the contents of this message is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and delete and destroy all copies of this message. Thank you.
</div>

    </body>
</html>