<!DOCTYPE html>
<html>
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <style>
		body{
			font: 12px Arial, sans-serif;
		}
		
		.small {
			font: italic 0.8em Arial, sans-serif;
		}
		</style>
    </head>
    
    
    
    <body>
        Thank you for your interest in Visiting Nurse Service of New York Hospice. As the largest provider of hospice care in NYC, servicing all 5 boroughs, our goal is to provide exemplary hospice care services to ensure the highest level of physical and emotional comfort, dignity and support to all patients and families.
      
      <p>
        We look forward to speaking with you soon. Please expect a call from us to discuss your immediate concerns and needs.
	  </p>

	<p>
	Warmest regards, <br/>
	
	<span style="color:#1e94bc">VNSNY Hospice and Palliative Care</span>
	</p>
	<p>
	  <img src="cid:vnsnyThumbNail" height="77"/>
      <img src="cid:veteransThumbNail" />
	</p>
	<p>     
	    Visiting Nurse Service of New York <br/>
		220 East 42nd Street New York, NY 10017 <br/>
		T: 212-609-1900 <br/>
		F: 212-290-1825 <br/>
		<a href="http://www.vnsny.org">www.vnsny.org</a> <br />
		<div class="small">
		This electronic message is intended to be for the use only of the named recipient, and may contain information from Visiting Nurse Service of New York and/or its affiliates and subsidiaries ("VNSNY") that is confidential or privileged, or protected health information from VNSNY that is confidential under HIPAA. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of the contents of this message is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and delete and destroy all copies of this message. Thank you.
		</div>
    </p>
      
    </body>
</html>