spring.profiles.active=@spring.profiles.active@

spring.jackson.serialization.indent-output=true


#SES Email config
spring.mail.host=email-smtp.us-east-1.amazonaws.com
spring.mail.username=AKIAUZ3DBCKETVYGAXNS
spring.mail.password=BJe/P8jNBljHA0H82TUsupokgfSZhZxTfxRIqo3B6BLf
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Specific properties
hospice.referral.email=HospiceReferral@vnsny.org

#base64 encoded from vnsny_referral_service
service.passcode=dm5zbnlfcmVmZXJyYWxfc2VydmljZQ==

#logging controls
logging.file.name=/opt/appsData/ReferService/hos-referral-service.log
logging.file.max-size=5MB
logging.file.max-history=3
logging.level.root=info
logging.level.org.vnsny.ref=debug

#report
report.file.path=/opt/appsData/ReferService/referrals
report.receipient.email=HospiceIntakeCoordinators@vnsny.org,HospiceIntakeAssociates@vnsny.org,arlene.duran@vnsny.org,Gerard.Christophers@vnsny.org
#  Cc: Arlene Duran and Gerard Christopher
report.receipient.email.weekly=HosIntakeManagement@vnsny.org
report.receipient.email.monthly=HosIntakeManagement@vnsny.org
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB